### ISSUE TITLE
Scene and character lines for proof of concept

### ISSUE THREAD

**Issue by ExcaliburZero** [Infinite-Dango-Studios/ganbatte#4]
For the proof of concept we will need a basic, simple scene involving maybe two or three characters.

I know Sabre-Hectae has some scenes ready, and we may be able to use one of those or another scene. The characters in the scene will need to be established in order to assist the artists with #3.

So we need to:
- [x] Decide upon the scene to use for the proof of concept
- [x] Decide what characters will be in the scene
- [x] Get the scene ready for the proof of concept

**Comment by juanitaylor** [comment]
If I need to have art for that scene I need to have a copy of that scene. If someone could get that to me that would be awesome!

**Comment by Sabre-Hecate** [comment]
Uhh, here's a scene from the script I guess:

Kosuke
(disappointed)
“Oh….OK, Haruki-kun. Uh…have fun.”

Misaki
(excited)
“YAY! YOU MADE THE RIGHT CHOICE, HARUKI-KUN! THIS’LL BE REALLY FUN!”

Haruki
“Oh…haha, you seem pretty excited…”

Misaki
(still excited)
“I AM! RIGHT THIS WAY, HARUKI-KUN!”

Misaki grabs my wrist and pulls me away from the dining room at a run. I’m happy to be spending this time with her, but she practically drags me across the carpet as we tear through the halls. She pulls me up the stairs, and we enter the first room on the left. 
(Scene switch to Misaki’s room. No one on screen)
Her room is nice, if a little messy. It’s a lot like my room, although more personalized. Her bed is covered in bright purple sheets, and a little stuffed turtle sits atop them. Pictures cover her walls, mostly of her, Kosuke and her parents. A few pictures depict me and Misaki and a few others are just me. In truth, I do not remember when a few of them were taken, and I am not looking at the camera in them. On her desk sits a little pink book that I assume is the infamous diary, and I cautiously walk over to it. A loose paper is sticking out and I glance at it. It’s a sketch in pencil of a man. Upon further inspection, he is completely naked with the exception of a single, strategically placed heart. My eyes widen as I recognize the face…I’m fairly certain that it’s mine. 

Haruki
“Uh…you…uh…drew this?”

I’ve never seen a face go so red so quickly. 
(Misaki is now on screen)

Misaki
(blushing)
“N-NO! I-I MEAN, THAT’S NOTHING! ER, I MEAN…DON’T LOOK AT OTHER PEOPLE’S PERSONAL STUFF, IDIOT! ER…UH…HEY, LOOK MY BOOKSHELF, UH, LET’S LOOK AT BOOKS!”

Her face is the deepest shade of scarlet I have ever seen as she quickly pushes the sketch back into the depths of the notebook. I feel myself blushing a little too, this is kind of awkward. 

Misaki
“So…Haruki-kun, um, what kind of books do you like?”

Haruki
“Um, a lot of things…most recently I’ve been reading Tokyo Ghoul.”

Misaki
(excited)
“Ooh, I have all of that, do you need the next book?” 

Haruki
“No, I’m on book 13 and I already have the 14th.” 

Misaki
(normal)
“Oh, ok. Have you read Ouran High School Host Club? Elfen Lied? Watamote?”
She pulls the first book in each of these series’ out as she says their names. And then, she gets a devious grin.
(evil smile)
“Or maybe, you’re more into this, Haruki-kun?”
She pulls out two more books.
“Want to borrow my Sakura Trick or Girl Friends? Or maybe…”
She drops all the books she is holding and moves quickly over to her bed. She pulls out a pink glittery box that says “Misaki’s childhood stuff”. When she lifts off the lid and removes the false bottom, I gasp. In her box are piles and piles of hentai and erotic dojinshi.  She looks up at me with a mischievous glint in her eyes. 
“Is this what you want, Haruki-kun?”

Haruki
“I…er…wow, you sure have a wide range of genres…” 

Misaki
(smirk)
“You look kind of uncomfortable, Haruki-kun.”
She puts the lid back on the hentai box and slides it under her bed. 
“Don’t be an idiot, I’m just holding onto those for my friend.”

Haruki
“Mhm…suuuuure.”

Misaki
(enraged blush? Embarrassed blush?)
“L-LIKE YOU DON’T HAVE SECRET HENTAI. I’M GOING TO COME INTO YOUR ROOM WHEN YOU’RE SLEEPING AND SEARCH IT!”

Haruki
“Wow, that sounds a little creepy.”

_SFX SLAP_

Misaki
(enraged blush)
“SHUT UP, HARUKI-KUN!”
I laugh, despite the pain in my cheek. She’s acting just like we used to. We walk over to her bookshelf once more and I grab her copy of Fruits Basket. 

Haruki
“Can I take this?”

Misaki
(normal)
“Fruits Basket? You haven’t read that yet? Sure, go ahead!”

Haruki
“Thanks!” 
I grab her copies of Fruits Basket, and I stack them up in my arms. 

Misaki
(smile or normal?)
“Hey, Haruki-kun, remember when we used to play Fruits Basket together in grade school? WE SHOULD PLAY IT AGAIN RIGHT NOW!”

I smile, remembering my childhood school days with Kosuke and Misaki. We did used to play Fruits Basket a lot. Although I haven’t played it since I moved away. 

Haruki
“That sounds fun…but we can’t play Fruits Basket now…it requires a large group! Even if we could get Kosuke and your parents, we still wouldn’t have enough people for a proper game of it. Maybe in the future, when I have some more friends.”

Misaki
(excited)
“TOTALLY! We could probably get Riku-senpai and Kokona-chan from work to play! Ooh, and Sora-kun and Yuta-kun and Megumi-chan!”

I recognize many of the names from elementary school. 

Haruki
“The same ones who went to our school? They all work there?”

Misaki
“Yup! They sure do! Riku-senpai went there too, but you probably don’t remember him because he was three years ahead of us.”

Haruki
“Yeah…”

I’ve grown tired of carrying all these books, they’re getting heavy. 

Haruki
“I guess I should probably go back to my room now.”

Misaki
“No you don’t!”
She moves across the room and closes the door.
“C’mon, you promised to have fun with me all night, you can’t go to bed now! It’s way too early!”

Haruki
“Well, I mean, Fruits Basket is 23 books, that’s enough for now, I don’t need anything else to read.”

Misaki
“So let’s do something else fun! Like a dramatic reading or something! YEAH, LET’S DO THAT!”

She moves over to her bookshelf and begins looking through all her options. 

Haruki
“Haha, OK, but nothing from the hentai box, OK?”

Misaki
(smirk)
“Are you sureeeeeee?”

Haruki
“Yes!”

She laughs, and so do I. In the end, we read various scenes from Black Butler. She plays Sebastian and has me play Ciel. It’s pretty fun, and we make it through the first ten books, each of us taking on more and more characters as the series goes on. She takes Finny, I take Meyrin and Baldo. She gets Madam Red and Lau, I get Grell. In the end, it’s a lot of fun. Soon, it is pitch black outside her window. I am reading for the Undertaker when a knock on the door silences my speech.
(Misaki and Ms. Kosuke on the screen)

Ms. Kosuke
(horrified)
“Do either of you have any idea what time it is!? I thought Haruki went back to his room hours ago!”

Haruki
“W-what time is it!?”

Ms. Kosuke
“Ten minutes to midnight!” 

Misaki
(horrified)
“WHAT!?”

Ms. Kosuke
(normal)
“You should go to sleep, Misaki-chan. You too, Haruchan. In separate bedrooms.”

She smiles slightly, and exits the room with a polite nod.

Misaki
(furious blush)
“HOW DID YOU LET IT GET SO LATE, IDIOT?”

I don’t see why she’s so angry at me. She is the one who kept me here for our theatrical reading of Black Butler. 

Haruki
“Well, I’m going to be going now. This was fun, though!” 

I pick up my copies of Fruits Basket, and I quickly exit the room, closing her door behind me. 
(Misaki no longer on screen. Probably shouldn’t still be her room?)
When I pass Kosuke’s room on the way back to my own, it is dark. I’d planned to say hello to him, but it appears that he is already asleep. 
(no one on screen, Haruki’s room)
In my room, I place my newly acquired books on the bedside table. I yawn, and decide that it is too late to start the series tonight. Turning off the light, I climb into bed and fall asleep.

**Comment by Sabre-Hecate** [comment]
Or, for more characters:

Misaki 
“Dinner time, Haruki-kun~!!!!” 

When Kosuke and I arrived in the dining room, the table had been set with plates of Chirashizushi, Tempura and Dango. All of my favorites. I guess Misaki must have remembered, we did eat a lot together as children. 

Misaki
 “Do you like it, Haruki-kun? I made it special for you!”

Haruki
“Yeah, it’s all my favorites! Thank you.” 

Kosuke
(appears on screen)
“Um, hey sis, I’m here too.”

Misaki
(annoyed)
“HARUKI-KUN IS THE GUEST!” 

Kosuke
(smug)
“Well, you may have made him dinner, but I played video games with him and he let me borrow all his copies of No. 6.” 

Misaki
(annoyed)
“Really? Well maybe I have some books that he wants. Hey Haruki-kun, want to come to my room after dinner and check out my light novels and manga? I have, um, Spice and Wolf, and Black Bullet and Durarara!! and—“ 

Kosuke
(angry)
“HEY! HARUKI-KUN PROMISED TO PLAY MORE SMASH BROS AFTER DINNER WITH ME!”

They’re practically screaming at each other now, and I feel a blush burn on my cheeks.

Misaki
(angry)
“YOU’VE HAD HIM THE ENTIRE TIME HE’S BEEN HERE!”

Kosuke
(angry)
“YOU DO REALIZE THAT IT’S ONLY BEEN, LIKE, AN HOUR, RIGHT? AND BESIDES, HE’S MY BEST FRIEND!” 

I smile awkwardly. Are they fighting over me? Living here is certainly going to be interesting. 

Haruki
“Um….I’m kinda hungry, maybe we can just have dinner? I can decide what I want to do later.” 

They seem to remember that I’m there, and they both blush. 

Kosuke
(blush)
“Oh, haha, sorry, Haruki-kun, I sort of forgot that you were there for a minute.”

Misaki
(blush)
“Sorry that my brother’s such an idiot, Haruki-kun!”

I’m not really sure how to respond to the two of them so I just laugh and we all sit down at the table. For a few minutes, the only noises are the cacophony of noises which typically accompany eating. Both Kosuke and Misaki are eating quietly and won’t make eye contact to me. I suppose that they’re guilty about fighting over me. Finally, Mr. Kasai speaks up.

(Mr. and Mrs. Kasai are on screen)

Mr. Kasai
“So, Haruchan, what are your plans for this summer?”

I sit silently for a few moments, taking another bite of Chirashizushi. I realize now just how poorly planned this trip is. I guess I just decided to come to Maura to see Kosuke and Misaki. But now the question’s been asked and he’s waiting for a response. If I don’t speak up now, he could kick me out! It could ruin the entire trip. Possibly. 

Haruki
“Um….I guess I want to meet some interesting people? And I should probably get a job.” 

Ms. Kasi
“Do you have any ideas for employment?”

I think it over for a moment before shaking my head. I don’t really know who’s hiring in Maura at the moment. 

(Kosuke and Misaki on screen replacing the parents)

Misaki
“YOU SHOULD COME WORK AT THE CAFÉ!”

She practically jumps out of her seat as she says it. These guys sure are eager to spend time with me.

Haruki
“What café?”

Kosuke
(confused)
“I never told you, Haruki-kun? Misaki and I work at a little café in town. The coworkers are all pretty great. You’ll love Kokona-chan, she’s super sweet. The customers are all really interesting too. Plus, our boss, Riku-san is totally cool. He’ll probably hire you without too much convincing.”  

Haruki
“Ehh, I don’t know…”

It sounds like a good job, to be honest. It sounds like I’ll meet some interesting people, and I’ll be able to get the job without much of a struggle. That’s always a bonus. And yet, at the same time, I’ve never really pictured myself working at a café. It doesn’t really seem like my sort of thing. 

Kosuke
(upset?)
“Aww, C’mon! It could be a lot of fun…”

Misaki
(smirk)
“Plus you’ll get to see me in my cute uniform~! Every day! What else could you possibly want?”

I feel a deep blush erupt on my cheeks, and I try not to look Misaki directly in the eye. I see Mr. and Ms. Kasai looking back and forth between me and Misaki, and I can tell that they are reconsidering allowing us to sleep in the same house. 

Haruki
“Haha, well…when you put it like that!”

Kosuke
(beaming)
“GREAT! Misaki and I have work tomorrow, so I can introduce you to Riku-san then!” 

I nod my agreement, it sounds good. In truth, I was hoping for a little time to relax before getting too busy, but this job sounds fun at least. 

Dinner is over not long after that, and both Kosuke and Misaki look at me expectantly after all the dishes have been cleared. It suddenly dawns on me that I can’t put off the decision any longer. I’ll have to either go to Misaki’s room or to Kosuke’s. But which one should I choose?

Kosuke
“So, Haruki-kun, what’s happening now?”

Misaki
“Yeah, Haruki-kun, did you decide where you want to go?”

**Comment by ExcaliburZero** [comment]
I looked over the script, and it looks quite good so far. Here, have this :dango:.

I compiled a list of the characters in the scene, and will put it up on #3 as well:
- Haruki
- Kosuke
- Misaki
- Ms. Kasai
- Mr. Kasai

Though, you may want to post scripts in a format where the speaker names are bolded, and the character thoughts are italicized. See this page on how to do that: https://guides.github.com/features/mastering-markdown/

**Comment by ExcaliburZero** [comment]
@Sabre-Hecate
I have started working on the coding of the scene, see #5. I got the entire first post of the scene done, but I was wondering how you want to integrate it with the second post of the scene. How do those two parts fit together / transition?

**Comment by juanitaylor** [comment]
whew that's a long scene, haha XD

**Comment by ExcaliburZero** [comment]
@Sabre-Hecate 
Also, one more thing that we need to do is we need to come up with a corresponding color for each of the characters. The character's color will be used in the displaying of their name. The name colors are in hexadecimal format (ex. #000000, #FFF000).

Also, here is a screenshot from the game so far to show you an example of the character text colors.

![sc - 01](https://cloud.githubusercontent.com/assets/4276196/6140494/92512d1e-b166-11e4-8421-ab7de0f0929f.png)

So, we need the following:
- [x] Character name colors for Haruki, Kosuke, Misaki, Ms. Kasai, and Mr. Kasai.

**Comment by Sabre-Hecate** [comment]
Yay, you gave me dango~! _eats it while looking over the other comments_

OK, so, actually, the second scene I posted is BEFORE the first scene. And I cut out the connecting part. These are just excerpts. I'm still working on finding the file in my folders (I open in from my word document's "recently opened") to send to you. I think I'm going to put it on a flashdrive or copy it to a new document >.< Then you can see it. 

I like green for Haruchan. Hmm. Kosuke can be powder blue. I want Pink for either Loli or Kokona. Yuuki gets orange. Purple goes to either Kokona or Loli. THERE ARE SO FEW COLORS >.< hmm...yellow for Misaki. The parents can share a light lavender? Unless no one can share? Lav for the mom and, um, grey-navy for the dad.

**Comment by Sabre-Hecate** [comment]
HEY I FIGURED OUT ITALICS ALL ON MY OWN...

-IS THIS BOLD-

**Comment by Sabre-Hecate** [comment]
^evidently not

**Comment by ExcaliburZero** [comment]
@Sabre-Hecate 
For the markdown syntax (italics, bold, etc.), just read this page: https://guides.github.com/features/mastering-markdown/

Let me know when you get the scripts ready.

For the colors, can you come up with the hexadecimal codes (#0F0F0F, #000000, etc.) you want? Here are some tools to do that:
- List of Common Hexadecimal Colors: http://www.w3schools.com/html/html_colornames.asp
- Color Theme Designer: http://paletton.com/#uid=1000u0kllllaFw0g0qFqFg0w0aF

**Comment by Sabre-Hecate** [comment]
#00FF7F <- Haruchan
#40E0D0 <- Kosuke
#EE82EE <- Misaki
#FF00FF <- Kokona
#FF8C00 <- Yuuki
#B22222 <- Otaku
#ADFF2F <- Athlete
#FF69B4 <- Loli
#5F9EA0 <- All Minor Characters (can I do that?) (Riku, Mom, Dad, Coach, Boss, Rapist, etc.) 

I already sent you the script as it currently stands ^^

**Comment by ExcaliburZero** [comment]
@Sabre-Hecate 
I have added in the character colors for the characters that have been coded in so far. I will add the other ones in as needed.

I have also stared working on coding the script that you sent me. The only changes I noticed that should be made are that there is a bit too much use of Caps Lock, so you may want to remove some of the Caps Lock usage. Some is fine, but it's a bit too much right now. You also should look through all the uses of name endings as some use a dash, while others don't. (ex. Harukikun vs. Haruki-kun)

**Comment by ExcaliburZero** [comment]
I have updated the repository to all of the content included in the script sent to me by Sabre-Hecate. See 4bafa76c177cefa137d3978538ed21a2fc062c5d.

**Comment by Sabre-Hecate** [comment]
Yeah, I'm embarrassingly not 100% on how honorifics work? I've seen them written both ways. And I know that sometimes you're supposed to cut off letters too ex: Haruki -> Haruchan. Does anyone know the actual rules???

**Comment by ExcaliburZero** [comment]
@Sabre-Hecate 
Well from what I could find on Wikipedia it looks like the dash is usually used (ex. "Haru-chan"). As for the cutting off of letters:

> Dropping the honorific suffix when referring to one's interlocutor, which is known to as yobisute (呼び捨て?), implies a high degree of intimacy and is generally reserved for one's spouse, younger family members, social inferiors (as in a teacher addressing students in traditional arts), and very close friends. Within sports teams or among classmates, where the interlocutors approximately have the same age or seniority, it can also be acceptable to use family names without honorifics. Some people in the younger generation (roughly "born since 1970") prefer to be referred to without an honorific, however, and drop honorifics as a sign of informality even with casual acquaintances.

**Comment by Sabre-Hecate** [comment]
Shit. I just realized that Haruki recognizing Yuta, Megumi and Sora from elementary school makes NO sense. He didn't grow up in Maura. Neither did Kosuke and Misaki. I mean, yeah, Kosuke, Haruki and Misaki played Fruits Basket together in Elementary school, but there's no way that Yuta, Megumi and Sora played it with them unless they ALL somehow moved from the same village. Now, I have a minor possible fix for this. The Kasai's moved to Maura because Ms. Kasai's medical research company relocated to Maura. Theoretically, Yuta, Megumi and Sora could all have been children of other researchers. So I can do that, or I can remove references to a shared childhood. What do we want?

**Comment by ExcaliburZero** [comment]
@Sabre-Hecate 
I think removing the references to a shared childhood might be the better option. It seems like a little bit of a stretch to have all of those characters happen to have researchers as parents.

Plus I think you might be able to do character intros for the cafe workers a bit more easily that way, as Haruki will be learning about them along with the player.

**Comment by Sabre-Hecate** [comment]
I figured as much. They're ridiculously minor characters, they aren't even getting character arcs, but I still need them believable. 

Meanwhile in scriptwriter land I'm over here freaking out over how adorable Kosuke X Haruki is. Definitely my favorite ship that I didn't intend to include.

**Comment by Sabre-Hecate** [comment]
I hope we have a slap sound effect. I'm being kinda liberal with that one in my script.

**Comment by ExcaliburZero** [comment]
Yep.

If you want to do an arc for them you certainly can.

We should be able to get a slap effect.

Also, on another note, I'm not sure how exactly you want to handle path branching in terms of the players decisions that occur earlier on. For example, getting into story arcs based on how many positive interactions Haruki has with a character. I'd recommend having character points, where certain plot points would yield certain character points that would indicate Haruki's closeness with that character, and yield different plot points.

**Comment by Sabre-Hecate** [comment]
I'll include one for them if I can think of one, but they're mostly just stock characters ATM, so this place looks like an actual business. 

Good. Tsundere's have to slap. 

Eeek. This is literally the hardest part. I'm struggling to figure out how the point system is going to work, and mostly I'm just trying to get the material down ATM.

**Comment by ExcaliburZero** [comment]
Just to clear up, with the adding of the arc I was referring to Kosuke X Haruki.

The point system shouldn't be too difficult to figure out. As you said, we should get some of the writing down first, and the point system shouldn't be too difficult to implement.

**Comment by Sabre-Hecate** [comment]
HAHA AS IF I DIDN'T ALREADY ADD ENOUGH HINTING AT KOSUKE X HARUKI YAOI TO MAKE A LACK OF HARUKI X KOSUKE YAOI (IF ENOUGH KOSUKE POINTS ARE ACHIEVED) A SEVERE DISAPPOINTMENT TO THE PLAYER. 

Right. I think Kokona's death will be the main point for the beginning of serious arcs. All the stuff prior to her death will mostly be gaining points with your favorite lovers.

**Comment by ExcaliburZero** [comment]
Okay then.

Yeah, that sounds like a good idea.

Also, if you want me to implement the "Harvest Moon-like" character heart display feature I can try working on that. And of course it could be hidden for Kosuke if you want.

**Comment by Sabre-Hecate** [comment]
Haha, hey, when I see a ship I like and I have opportunity, I implement it. 

Yup. Kokona's death is pretty much a midpoint in that way. 

That would be pretty cool, I think. I've made Kosuke's interest in Haruki a little obvious, but hiding it would be cool. Until it's suddenly revealed.

**Comment by ExcaliburZero** [comment]
So which of the character will have arcs, and thus need heart meters?

**Comment by Sabre-Hecate** [comment]
Well, the lovers.

Otaku, Misaki, Kosuke, Yuuki, Athlete, Loli and Kokona (so the players expect that she can be saved)

**Comment by ExcaliburZero** [comment]
I added notes to the character list (#2) for those characters, indicating that the will be romance-able. (Is that a word?)

**Comment by Sabre-Hecate** [comment]
It is indeed a word now. And I gave everyone names ^^

Everyone who isn't the Coach, Rapist, Club owner....OK _MOST_ PEOPLE HAVE NAMES NOW. IT'S A START.

**Comment by ExcaliburZero** [comment]
Also, how much of the content do you want to be in the proof of concept? Where do you want the proof of concept to end?

**Comment by ExcaliburZero** [comment]
Also, I created an issue specifically for the heart meters at #7.

**Comment by Sabre-Hecate** [comment]
ENd...? Uh...I didn't think about it >.<

**Comment by Sabre-Hecate** [comment]
Also, what's the max number of characters that can be on screen at once? Right now I keep it at two, but three may be more convenient at times.

**Comment by ExcaliburZero** [comment]
Actually, we probably won't need to have a set end point for the proof of concept, as the proof of concept is really more of a guideline than a set development point.

I don't know exactly what the limit for characters is, but 2-3 max should be a good guideline.

**Comment by ExcaliburZero** [comment]
@Sabre-Hecate 
I've been working on adding more of the script that you have sent me. I noticed that you change the character points directly at the choices, however I think it may be better to change the character points throughout the choice line.

For example, in the first choice if Haruki answers "T-this is all very sudden...but...I’d be willing to try...". Misaki suddenly gets closer to Haruki. While it would make more sense to have her gain character points / get closer to him when saying the line "Did you really mean it?".

**Comment by Sabre-Hecate** [comment]
I'm just putting those there as placeholder indications of where points are gained/lost. 

I figured I'd leave points programming up to you. Feel free to place them where you please, and yes it would make sense for it to happen at lines.

**Comment by ExcaliburZero** [comment]
@Sabre-Hecate 
Okay, sounds good. I have moved around the character point changes in 27ff4eabf00c34d57d5d9794271290ae96a06eb7. Let me know if you are good with those placings.

**Comment by ExcaliburZero** [comment]
I've been working more on updating the scripting and I was wondering out one line.

> Yuuki: I’m going to lay a curse on you for that! I was talking to usa-chan and you interrupted me.

Would "usa-chan" be capitalized in the line or is it supposed to be lowercase?

**Comment by Sabre-Hecate** [comment]
Usa-chan would be capitalized. It's her lil sis.

**Comment by Sabre-Hecate** [comment]
Usa-chan would be capitalized. It's her lil sis.

**Comment by ExcaliburZero** [comment]
@Sabre-Hecate 
I've fixed it with commit e0eeffe63c307fb7d269011468b026bbf4d2bcd7 .

**Comment by ExcaliburZero** [comment]
Since this issue is somewhat vague and not currently being used, I will now close it.
